# Generated by Django 4.2.15 on 2024-08-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='admin_confirmation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='escrow_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='escrow_type',
            field=models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked')], default='unlocked', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
