# Generated by Django 4.2.15 on 2024-08-24 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_listing_admin_confirmation_listing_escrow_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='notification_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
