# Generated by Django 4.2.15 on 2024-08-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_listing_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='marketplace_notification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
