# Generated by Django 4.2.15 on 2024-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='template_name',
            field=models.CharField(default='tool_template', max_length=100, unique=True),
        ),
    ]
