# Generated by Django 4.2.15 on 2024-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tool_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='template_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
