# Generated by Django 4.2.15 on 2024-08-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_tool_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
